version: 2.1

executors:
  builder:
    docker:
      - image: circleci/node:latest

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
    setup:
        executor: builder
        steps:
        - checkout
        - run:
            name: Update NPM
            command: 'sudo npm install -g npm@latest'
        - restore_cache:
            name: Restore Yarn Package Cache
            keys:
                - yarn-packages-{{ checksum "yarn.lock" }}
        - run:
            name: Install Dependencies
            command: yarn install --frozen-lockfile
        - save_cache:
            name: Save Yarn Package Cache
            key: yarn-packages-{{ checksum "yarn.lock" }}
            paths:
                - ~/.cache/yarn
        - persist_to_workspace:
            root: .
            paths:
                - "*"

    lint:
        executor: builder
        steps:
            - attach_workspace:
                at: .
            - run:
                name: Create Reports Directory
                command: yarn run ci:init
            - run:
                name: Lint Test
                command: 'yarn lint:test'
            - store_artifacts:
                path: ./reports
            - store_test_results:
                path: ./reports

workflows:
    main:
        jobs:
            - setup
            - lint:
                requires: [ setup ]
            # See https://github.com/ChocPanda/cat-pun/issues/13
            # - test:
            #     requires: [ setup ]
            # - build:
            #     requires: [ lint, test ]
            # - publish-github-release:
            #     requires:
            #         - build
            #     filters:
            #         branches:
            #             only: master
            #         tags:
            #             only: /^\d+\.\d+\.\d+$/
